### ISSUE TITLE
TypeScript Issue with User Service

### ISSUE THREAD

**Issue by bcba25** [adrien2p/nestjs-sequelize-jwt#4]
Hi,
I've tried to start the project, and there are multiple issues like described below in a user service:

```
modules/users/user.service.ts (15,22): The 'this' context of type 'typeof Model' is not assignable to method's 'this' of type 'new () => User'.
  Cannot assign an abstract constructor type to a non-abstract constructor type. (2684)
```

Any idea on how to fix that ?

**Comment by adrien2p** [comment]
Hey @hxdef2517 You can pull back the project and start it. I've fixed the injection type into the userService
